# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

 production:
   qiniu_access_key: FW9g0uj2Z3Aa2_N1mpOCPCYMma6SsYiWS6ur7rNV  # 你的 qiniu AccessKey
   qiniu_secret_key: 5RuROIl_oTEdU3Z7e0mUOJTJqhJsH_afMsYRN4Xr  # 你的 qiniu SecretKey
   qiniu_bucket: jdstore-demo  # 你的 qiniu bucket
   qiniu_bucket_domain: ops9eqy9m.bkt.clouddn.com  # 你的 qiniu bucket domain
   SEND_CLOUD_USER_NAME: "yo7588_test_gsylEb" # 你的 API_USER
   SEND_CLOUD_USER_KEY: "tmjYBoIgTN1eyp4N" # 你的 API_KEY
   PROJECT_ID:  "144696"
   PROJECT_KEY: "759cd4f664387aa78bd3023c3d95584a"



 development:
   qiniu_access_key: FW9g0uj2Z3Aa2_N1mpOCPCYMma6SsYiWS6ur7rNV  # 你的 qiniu AccessKey
   qiniu_secret_key: 5RuROIl_oTEdU3Z7e0mUOJTJqhJsH_afMsYRN4Xr  # 你的 qiniu SecretKey
   qiniu_bucket: jdstore-demo  # 你的 qiniu bucket
   qiniu_bucket_domain: ops9eqy9m.bkt.clouddn.com  # 你的 qiniu bucket domain
   SEND_CLOUD_USER_NAME: "yo7588_test_gsylEb" # 你的 API_USER
   SEND_CLOUD_USER_KEY: "tmjYBoIgTN1eyp4N" # 你的 API_KEY
   PROJECT_ID: "144696"
   PROJECT_KEY: "759cd4f664387aa78bd3023c3d95584a"
